Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 44, in find_summoner
    get_matches_for_summoner(summoner_info['id'])
TypeError: string indices must be integers, not str
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 44, in find_summoner
    get_matches_for_summoner(summoner_info['id'])
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 32, in get_matches_for_summoner
    get_match_history('na', summoner_id, count, count + 15)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 23, in get_match_history
    url = constants.api_url(constants.K_LOL_MATCH_HISTORY, region, [summoner_id], [begin_index, end_index])
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/constants.py", line 70, in api_url
    url = '{0}/{1}?{query}api_key={2}'.format(BASE_URL, call, RIOT_API_KEY)
KeyError: 'query'
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 44, in find_summoner
    get_matches_for_summoner(summoner_info['id'])
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 32, in get_matches_for_summoner
    get_match_history('na', summoner_id, count, count + 15)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 23, in get_match_history
    url = constants.api_url(constants.K_LOL_MATCH_HISTORY, region, [summoner_id], [begin_index, end_index])
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/constants.py", line 81, in api_url
    query_param = query_params + param + '&'
TypeError: can only concatenate list (not "str") to list
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 130, in get_response
    % (callback.__module__, view_name))
ValueError: The view lemonnotes.views.find_summoner didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 44, in find_summoner
    url = constants.api_url(constants.K_LOL_SUMMONER_BY_NAME, 'na', summoner_name, None)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/constants.py", line 80, in api_url
    for param in query_params:
TypeError: 'NoneType' object is not iterable
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 44, in find_summoner
    url = constants.api_url(constants.K_LOL_SUMMONER_BY_NAME, 'na', summoner_name, None)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/constants.py", line 80, in api_url
    for param in query_params:
TypeError: 'NoneType' object is not iterable
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 49, in find_summoner
    get_matches_for_summoner(summoner_info['id'])
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 36, in get_matches_for_summoner
    matches = matches + get_match_history('na', summoner_id, count, count + 15)
TypeError: can only concatenate list (not "NoneType") to list
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 51, in find_summoner
    matches = get_matches_for_summoner(summoner_info['id'], 100)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 38, in get_matches_for_summoner
    matches = matches + get_match_history('na', summoner_id, count, count + 15)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 28, in get_match_history
    matches = r.json()['matches']
KeyError: 'matches'
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 51, in find_summoner
    matches = get_matches_for_summoner(summoner_info['id'], 100)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 38, in get_matches_for_summoner
    matches = matches + get_match_history('na', summoner_id, count, count + 15)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 28, in get_match_history
    matches = r.json()['matches']
KeyError: 'matches'
Internal Server Error: /lemonnotes/find_summoner/
Traceback (most recent call last):
  File "/Users/chrisf/.virtualenvs/lemonnotes/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 51, in find_summoner
    matches = get_matches_for_summoner(summoner_info['id'], 100)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 38, in get_matches_for_summoner
    matches = matches + get_match_history('na', summoner_id, count, count + fetch_limit)
  File "/Users/chrisf/projects/lemonnotes_web/lemonnotes/views.py", line 28, in get_match_history
    matches = r.json()['matches']
KeyError: 'matches'
